### PR TITLE
CMake building with automatic downloading/building/installing orcania (working on Linux)

### PR DESCRIPTION
**Pull request by silvioprog**

### CODE REVIEW

**Comment by silvioprog** [comment]
To test it, just:

```bash
git clone https://github.com/silvioprog/yder.git
git checkout cmake
cd yder/
mkdir build
cd build/
cmake -DBUILD_TESTING=ON -DCMAKE_SKIP_RPATH=ON ..
sudo make install/strip
```

It will install (striped) Orcania and Yder returning some log like this:

image

and finally you may get info from Orcania/Yder:

image

Note: tested only on Linux (Xubuntu 16.04 64 bits). I'll going to test it on Windows tomorrow. (now is `Sun Jan 28 02:04:04 -03 2018` :-) )

**Comment by babelouest** [comment]
I've tested it and it seems to work for me, I have a couple of questions though:

- Is it possible to download and extract a `.tar.gz` archive based on its url instead of `git clone`'ing it ?
- Why do you add the option `-DCMAKE_SKIP_RPATH=ON` in your example? I guess it's not mandatory. At least I couldn't find a difference in my tests.

**Comment by babelouest** [comment]
to be more specific about the `tar.gz` archive, I used the url `URL https://github.com/babelouest/orcania/archive/v1.2.0-b.tar.gz` in my cmake branch of yder, to download the correct archive and this archive only.

It's a nice to have rather than a bug, but it could allow to install the libraries in a fresh install with minimized dependencies.

**Comment by silvioprog** [comment]
It works with tar files, however I've used from trunk because latest sent fixes hehe.

**Comment by silvioprog** [comment]
`-DCMAKE_SKIP_RPATH=ON` was just to show that our building system allows the programmer to ignore `rpath` hints.

**Comment by babelouest** [comment]
How do I use it with tar files? I've tried with the option `url` but it didn't seem to work

**Comment by babelouest** [comment]
Never mind, found it! :)

**Comment by silvioprog** [comment]
Awesome! :-)

**Comment by silvioprog** [comment]
Worked like a charm on Windows. My steps was:

```bash
git clone https://github.com/babelouest/yder.git && cd yder/ && git checkout cmake
mkdir build && cd build/
cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw32 ..
make install/strip
```
and the full log was:

image

same to the test:

image

I :heart: CMake!

**Pull request merged**
